name: 'Time of day check'
description: 'Prevents a pull request being merged after a certain time'
inputs:
  blocking-hour:  # id of input
    description: 'Blocking hour: "HH"'
    required: true
    default: 16
outputs:
  message: # id of output
    description: 'Action result'
runs:
  using: 'node12'
  main: 'index.js'
