on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  time_of_day_check_job:
    runs-on: ubuntu-latest
    name: Time of day check
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Time of day check action step
        uses: ./ # Uses an action in the root directory
        id: time-of-day-check
        with:
          blocking-hour: 11
